#!/bin/bash
sudo apt install qt5-default
sudo apt install libqt5serialport5
sudo apt install libqt5script5
sudo apt install libqt5qml5
sudo apt install libqt5quickwidgets5
sudo apt install qml-module-qtquick-controls
sudo apt install libsdl2
sudo apt install libqt5multimedia5-plugins