#!/bin/bash
sudo apt install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
sudo apt install qtcreator
sudo apt install qtdeclarative5-dev 
sudo apt install libqt5serialport5-dev
sudo apt install qtscript5-dev
sudo apt install qtmultimedia5-dev
sudo apt install libqt5opengl5-dev
sudo apt install libqt5multimedia5-plugins
sudo apt install libqt5svg5-dev
sudo apt install libudev-dev


